export const ACTIONS = {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  LOG_OUT: 'LOG_OUT',
  OPEN_ADD_VILLAIN_MENU: 'OPEN_ADD_VILLAIN_MENU',
  CLOSE_ADD_VILLAIN_MENU: 'CLOSE_ADD_VILLAIN_MENU'
};

export const FETCHES = {
  LOG_IN: 'LOG_IN',
  ADD_VILLAIN: 'ADD_VILLAIN',
  GET_VILLAINS: 'GET_VILLAINS',
  REMOVE_VILLAIN: 'REMOVE_VILLAIN',
  UPDATE_VILLAIN: 'UPDATE_VILLAIN',
  ADD_IMAGE: 'ADD_IMAGE'
};

export const PAGES = {
  LOG_IN: 'LOG IN',
  VILLAINS: 'VILLAINS',
  ADD_VILLAIN: 'ADD VILLAIN'
};
